name: sAIlor-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - fastapi>=0.104.0
  - uvicorn[standard]>=0.24.0
  - rasterio>=1.3.0
  - numpy>=1.24.0
  - pyproj>=3.6.0
  - pydantic>=2.0.0
  - scikit-learn>=1.3.0
  - pandas>=2.0.0
  - joblib>=1.3.0
  - requests>=2.31.0
  - python-dotenv>=1.0.0
  - shapely>=2.0.0
  - pip:
    - python-multipart>=0.0.6
